# Generated by Django 4.2.1 on 2023-06-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
