# Generated by Django 4.2.1 on 2023-06-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=999999999, max_length=100),
            preserve_default=False,
        ),
    ]
